int monsterCol = 10;
int monsterRow = 5;
String monsterImageWhite = "invader";
//String monsterImageRed = "RedInvader.png";
String shipImage = "Ship.png";
String bulletImage = "Bullet.png";
String blankImage = "Blank.png";
String explosionPrefix = "explosion";
String invaderExp = "invaderExplosion";
String explosionSoundFile = "ExplosionSound.mp3";
String invaderD = "InvaderDeath.png";
String invaderDSF = "InvaderDying.mp3";
String shipShootSF = "Shoot.wav";
String BGM1 = "BackgroundMusic1.mp3";
String BGM2 = "MenuMusic.mp3";

boolean firstRunThrough = true;
boolean paused = false;
String currentSong = "";
SoundFile Background1;
SoundFile Background2;
boolean playing = false;
float startingTime = 0;
//ArrayList<SoundFile> soundsPlaying;
SoundFile bulletSounds[];
int currentBulletSound = 0;
SoundFile explosionSounds[];
int currentExplosionSound = 0;
int menu = 1;
int buttonWidth = 500;
int buttonHeight = 100;
ArrayList<Button> buttons;
boolean buttonsAdded = false;
float lastShot = 0;
float delayShoot = .5;

boolean invisibleMonsters = false;
Sprite invaderDeath;
Animation explosion;
Sprite invaderExplosion;
PImage gameOverScreen;
int widthSpace = 20;
int heightSpace = 20;
int xmov = 10;
int ymov = 10;
int spriteDim = 50;
int bulletH = 6;
int widthFluff = 120;
int heightFluff = 200;
int counter = 0;
boolean sideways = false;
int monstersLeft = monsterCol * monsterRow;
boolean keys[]; //Have LEFT be index 0, RIGHT be index 1,space be index 2
int amtKeys = 3;
ArrayList<Sprite> bullets;
ArrayList<Sprite> exploding;
boolean attackingMonster = false;
int lastRow = monsterRow - 1;
int attackingRow = 0,attackingColumn = 0;
int attackmov = xmov;
int leftMostColumn = 0;
int rightMostColumn = monsterCol - 1;
int stage = 0;
boolean partyMode = false;
boolean strobeLights = false;
color backgroundColor = color(50);
String strobeLightsString = "on";
String partyModeString = "on";
String invisMonstersString = "on";
float scaleAmount = 0;
float changeScale = .02;
float boundaryScale = .09;
ArrayList<Sprite> fallingMonsters;
ArrayList<Point> fallingCoords;
char bulletType = 'R';
int shipHealth = 1;
int bulletDamage = 1;
ArrayList<PowerUp> powerUps;
int fireableBullets = 1;
int bulletsPerShot = 1;
int bulletSpeed = ymov;
Star stars[];

boolean gameOver = false;
int score = 0;

Sprite monsters[][];
Sprite ship;
Sprite bullet;

ArrayList<String> LeaderBoard;
Scanner input;
boolean inputtingName = false;
String name = "";
boolean enteredName = false;